mash-up-kr/mashup-server

- mashup-api/src/main/java/kr/mashup/branding/config/security/SecurityConfig.java
- mashup-api/src/main/java/kr/mashup/branding/ui/team/TeamAssembler.java
- mashup-api/src/main/java/kr/mashup/branding/ui/team/TeamController.java
- mashup-api/src/main/java/kr/mashup/branding/ui/team/TeamResponse.java
- mashup-api/src/test/java/kr/mashup/branding/ui/team/TeamControllerTest.java
- 로그인하지 않아도 팀목록조회 API 호출가능하게 변경
- 공통 응답 dto 적용
- 사용하지 않는 필드 제거 (createdAt, updatedAt)
- 테스트 추가
> feat: 팀 목록 조회 API 개선

- mashup-admin/src/main/java/kr/mashup/branding/facade/ProfileFacadeService.java
- mashup-admin/src/main/java/kr/mashup/branding/facade/application/form/ApplicationFormDeleteFailedException.java
- mashup-admin/src/main/java/kr/mashup/branding/facade/application/form/ApplicationFormFacadeServiceImpl.java
- mashup-domain/src/main/java/kr/mashup/branding/domain/ResultCode.java
- mashup-domain/src/main/java/kr/mashup/branding/domain/application/ApplicationRepository.java
- mashup-domain/src/main/java/kr/mashup/branding/domain/application/ApplicationService.java
- mashup-domain/src/main/java/kr/mashup/branding/domain/application/ApplicationServiceImpl.java
- mashup-domain/src/main/java/kr/mashup/branding/domain/application/form/ApplicationFormDeleteFailedException.java
- mashup-domain/src/main/java/kr/mashup/branding/domain/application/form/ApplicationFormServiceImpl.java
- mashup-domain/src/main/java/kr/mashup/branding/infrastructure/data/TestDataInitializer.java
기존 코드에서는 foreign key 때문에 지원서가 있으면 form 삭제가 불가능 했었습니다.
그래서 지원서가 있으면 ApplicationFormDeleteFailedException를 내려주게 수정 했습니다.
local, dev 환경에서는 해당 formId를 갖고 있는 application을 찾아서 먼저 삭제 하고 (이 과정에서 cascade 옵션이 걸려있는 applicationResult, confirmation 등은 함께 삭제됨) form을 삭제 하게 했습니다.
테스트 (O) - 수동 . . .
이게 form을 삭제하기 전에 application을 먼저 삭제 해야해서 전에 이야기했던 삭제 이벤트를 받아서 후처리는 못했고 profile에 따라서 먼제 application을 지울지 여부를 썼는데  그래서 profileFacadeService를 추가 했습니다 🙇‍♂️
> feat: local, dev 환경에서는 지원서가  있어도 설문지 삭제 가능

- mashup-domain/src/main/java/kr/mashup/branding/infrastructure/data/TestDataInitializer.java
- mashup-domain/src/main/java/kr/mashup/branding/infrastructure/test/NoopApplicationFormScheduleValidator.java
- mashup-domain/src/main/java/kr/mashup/branding/infrastructure/test/NoopApplicationScheduleValidator.java
`local`, `develop` 프로필이 활성화되어있으면 일정관련 검증 무시
`ignore-schedule-validation` 프로필이 활성화되어있으면 일정 관련 검증 무시
> feat: 일정검증 무시하게하는 profile 이름 변경

- gradle.properties
- mashup-admin/build.gradle
- mashup-admin/src/main/java/kr/mashup/branding/config/messageconverter/HTMLCharacterEscapes.java
- mashup-admin/src/main/java/kr/mashup/branding/config/messageconverter/MessageConverterConfig.java
- mashup-api/build.gradle
- mashup-api/src/main/java/kr/mashup/branding/config/messageconverter/HTMLCharacterEscapes.java
- mashup-api/src/main/java/kr/mashup/branding/config/messageconverter/MessageConverterConfig.java
- mashup-api/src/test/java/kr/mashup/branding/ui/team/TeamControllerTest.java
- HTML 태그 인코딩 기능 도움 받기 위해 org.apache.commons:commons-text 추가 
- 기존 ObjectMappter에 HTMLCharacterEscapes를 추가하여 MappingJackson2HttpMessageConverter 생성 후 빈으로 등록
- 테스트O
> feat: response body xss 처리

- mashup-api/src/main/java/kr/mashup/branding/ui/application/ApplicationStatusResponse.java
- 문제 상황 : 최종 발표 시간 이후 면접 불합격 상태가 내려옴
- 정상적인 상황 : 최종 발표 시간 이후 기한 만료 상태가 내려옴
미검토 케이스를 추가하여 문제 해결
> fix: 지원서 임시저장 상태에서 최종 발표 시간 이후 상태에 대한 이슈 해결

- mashup-domain/src/main/java/kr/mashup/branding/service/schedule/ScheduleService.java
- mashup-member/src/main/java/kr/mashup/branding/facade/schedule/ScheduleFacadeService.java
- mashup-member/src/main/java/kr/mashup/branding/ui/schedule/request/ScheduleCreateRequest.java
- 기존 body field를 generationId에서 generationNumber로 변경하였습니다.
> feat: 스케줄 생성시, 기수 숫자 받는 것으로 변경

- mashup-member/build.gradle
- mashup-member/src/main/java/kr/mashup/branding/security/SecurityConfig.java
아래 3개의 API 제외한 모든 API는 요청 시에 엑세스 토큰이 필요하도록 설정하였습니다.
- 회원가입 API
- 로그인 API
- 회원가입 코드 검증 API
> feat: security config 설정

- mashup-member/src/main/java/kr/mashup/branding/facade/schedule/ScheduleFacadeService.java
- mashup-member/src/main/java/kr/mashup/branding/ui/schedule/ScheduleController.java
- mashup-member/src/main/java/kr/mashup/branding/ui/schedule/response/Progress.java
- mashup-member/src/main/java/kr/mashup/branding/ui/schedule/response/ScheduleResponse.java
- mashup-member/src/main/java/kr/mashup/branding/ui/schedule/response/ScheduleResponseList.java
- mashup-member/src/main/java/kr/mashup/branding/ui/schedule/response/ScheduleResponseListWithProgress.java
- NOT_REGISTERED: 등록된 세미나가 없는 경우
- ON_GOING: 세미나가 존재하지만, 현재 날짜 이후로 등록된 세미나가 있는 경우
- DONE: 세미나가 존재하지만, 현재 날짜 이후로 등록된 세미나가 없는 경우
- 과거 스케줄인 경우: 음수값(-) 표시
- 현재 스케줄인 경우: 0 표시
- 미래 스케줄인 경우: 양수값(+) 표시
```
{
"code": "SUCCESS",
"message": "성공",
"data": {
"scheduleId": 3,
"name": "해커톤",
"dateCount": -3,
"startedAt": "2022-07-28T23:59:00",
"endedAt": "2022-07-28T23:59:00",
"generationNumber": 1,
}
}
```
```
{
"code": "SUCCESS",
"message": "성공",
"data": {
"progress": "DONE",
"dateCount": 0,
"scheduleList": [
{
"scheduleId": 1,
"name": "1차 정기 세미나",
"datCount": -29,
"startedAt": "2021-07-02T15:30:00",
"endedAt": "2021-07-02T16:30:00",
"generationNumber": 1,
"eventList": [
{
"eventId": 1,
"startedAt": "2022-05-02T15:30:00",
"endedAt": "2022-10-02T16:00:00",
```
> feat: 스케줄 조회 시, 스케줄 진행 상황 및 남은 기간 필드 추가

- mashup-member/src/main/java/kr/mashup/branding/facade/member/MemberFacadeService.java
- mashup-member/src/main/java/kr/mashup/branding/ui/member/request/SignUpRequest.java
- mashup-member/src/main/java/kr/mashup/branding/ui/member/response/MemberInfoResponse.java
- 회원가입 시에도 osType, fcmToken 정보를 업데이트 할 수 있도록 추가합니다.
> 푸시 알림 정보 업데이트 및 조회 추가

- mashup-admin/src/main/java/kr/mashup/branding/facade/schedule/ScheduleFacadeService.java
- mashup-domain/src/main/java/kr/mashup/branding/repository/schedule/ScheduleRepository.java
- mashup-domain/src/main/java/kr/mashup/branding/repository/schedule/ScheduleRepositoryCustom.java
- mashup-domain/src/main/java/kr/mashup/branding/repository/schedule/ScheduleRepositoryCustomImpl.java
- mashup-domain/src/main/java/kr/mashup/branding/service/schedule/ScheduleService.java
- mashup-member/src/main/java/kr/mashup/branding/facade/attendance/AttendanceFacadeService.java
- mashup-member/src/main/java/kr/mashup/branding/facade/schedule/ScheduleFacadeService.java
- 기능 수정
- 스케줄 상태값(`PUBLIC`, `ADMIN_ONLY`) 이 추가되었습니다.
- 멤버 모듈에서는 `PUBLIC` 상태인 스케줄만 조회하도록 변경하였습니다.
- 스케줄 단건 조회 시에 상태값을 포함하여 조회하는 메서드 추가
- 스케줄 다건 조회 시이 상태값이 있으면 해당 상태값만 / 없으면 모든 상태값 조회 하도록 조건 수정
> 스케줄 조회 시, 상태값 추가

- mashup-batch/src/main/java/kr/mashup/branding/facade/ScoreHistoryFacadeService.java
- mashup-domain/src/main/java/kr/mashup/branding/repository/attendance/CustomAttendanceRepository.java
- mashup-domain/src/main/java/kr/mashup/branding/repository/attendance/CustomAttendanceRepositoryImpl.java
- mashup-domain/src/main/java/kr/mashup/branding/repository/member/MemberRepositoryCustom.java
- mashup-domain/src/main/java/kr/mashup/branding/repository/member/MemberRepositoryCustomImpl.java
- mashup-domain/src/main/java/kr/mashup/branding/repository/schedule/ScheduleRepository.java
- mashup-domain/src/main/java/kr/mashup/branding/service/attendance/AttendanceService.java
- mashup-domain/src/main/java/kr/mashup/branding/service/member/MemberService.java
- mashup-domain/src/main/java/kr/mashup/branding/service/scorehistory/ScoreHistoryService.java
- 기능 수정
- 출석체크한 데이터가 경우에 결석으로 처리가 되지 않고 있습니다.
- 출석점수를 계산할 스케줄의 기수값을 기준으로 멤버를 조회합니다.
- 출석체크한 데이터가 모두/부분적으로 존재하는 경우 -> 존재하는 데이터로 출석점수 계산(기존로직)
- 출석체크한 데이터가 모두 없는 경우 -> 결석으로 처리(추가된 로직)
> 출석체크 없는 경우에 결석 처리 로직 추가

- mashup-domain/src/main/java/kr/mashup/branding/domain/member/Member.java
- mashup-domain/src/main/java/kr/mashup/branding/dto/member/MemberCreateDto.java
- mashup-domain/src/main/java/kr/mashup/branding/service/member/MemberService.java
- mashup-member/src/main/java/kr/mashup/branding/facade/member/MemberFacadeService.java
- 기능 수정
- 모바일에서 기본점수 타입이 없어서 회원가입시에 임시로 ATTENDACE로 변경하 부분 원복하였습니다.
- 회원가입 시에 멤버를 저장한 후에 fcm 관련 필드 업데이트 하는 로직에서 멤버 저장시에 같이 저장하는 방식으로 변경하였습니다.
> 회원가입 시 기본점수 부여 원복

- mashup-domain/src/main/java/kr/mashup/branding/domain/member/Member.java
- mashup-domain/src/main/java/kr/mashup/branding/infrastructure/pushnoti/FcmPushNotiService.java
- mashup-domain/src/main/java/kr/mashup/branding/service/member/MemberService.java
- mashup-member/src/main/java/kr/mashup/branding/facade/member/MemberFacadeService.java
- mashup-member/src/main/java/kr/mashup/branding/ui/member/request/PushNotificationRequest.java
- mashup-member/src/main/java/kr/mashup/branding/ui/member/response/AccessResponse.java
- mashup-member/src/main/java/kr/mashup/branding/ui/member/response/MemberInfoResponse.java
- 기능
- 당근 푸시 알림 필드가 추가합니다.
AS-IS
```java
private Boolean pushNotificationAgreed = true;
```
TO-BE
```java
private Boolean newsPushNotificationAgreed = true;        // 매시업 소식 알림 동의 여부
private Boolean danggnPushNotificationAgreed = true;   // 당근 푸시 알림 동의 여부
```
> 당근 푸시 알림 필드 추가

- mashup-domain/src/main/java/kr/mashup/branding/config/LocalCacheConfig.java
- mashup-domain/src/main/java/kr/mashup/branding/domain/pushnoti/vo/DanggnFirstRecordMemberUpdatedVo.java
- mashup-domain/src/main/java/kr/mashup/branding/domain/pushnoti/vo/DanggnFirstRecordPlatformUpdatedVo.java
- mashup-domain/src/main/java/kr/mashup/branding/service/danggn/DanggnCacheKey.java
- mashup-domain/src/main/java/kr/mashup/branding/service/danggn/DanggnCacheService.java
- mashup-domain/src/main/java/kr/mashup/branding/service/generation/GenerationService.java
- mashup-domain/src/main/java/kr/mashup/branding/service/member/MemberService.java
- mashup-domain/src/main/java/kr/mashup/branding/util/DateUtil.java
- mashup-member/build.gradle
- mashup-member/src/main/java/kr/mashup/branding/facade/danggn/DanggnFacadeService.java
- 기능
- 당근 랭킹 1위 업데이트 알림 구현합니다.
- 9시, 13시, 19시에 1등 업데이트 알림
- fyi; [회의록](https://www.notion.so/TF-11134e042443449b9d38dece8c191353?p=c0abd2ec4d5545a8b936dbf4f6596f91&pm=s)
- 현재 활동하고 있는 기수에게만 알림
- 당근 랭킹 1위 업데이트
- 현재 기준으로 활동하는 generation 조회(예외적인 케이스 제외하고 조회된 기수 1개)
- 각 generation 돌면서, 1등이 변경된 경우
- 랭킹 1 업데이트 푸시 알림 발송
- 캐시 업데이트
- 1등 변경조건
- 해당 Generation에 멤버가 1명이상 존재
- 캐시된 데이터가 존재하고, 캐시된 데이터와 최근 데이터가 다른 경우
> feat: 당근 랭킹 1위 업데이트 알림을 위한 캐시 구현

- mashup-domain/src/main/java/kr/mashup/branding/domain/ResultCode.java
- mashup-domain/src/main/java/kr/mashup/branding/domain/danggn/DanggnNotificationMemberRecord.java
- mashup-domain/src/main/java/kr/mashup/branding/domain/danggn/DanggnNotificationPlatformRecord.java
- mashup-domain/src/main/java/kr/mashup/branding/domain/danggn/DanggnRankingReward.java
- mashup-domain/src/main/java/kr/mashup/branding/domain/danggn/DanggnRankingRewardStatus.java
- mashup-domain/src/main/java/kr/mashup/branding/domain/danggn/DanggnRankingRound.java
- mashup-domain/src/main/java/kr/mashup/branding/domain/danggn/DanggnScore.java
- mashup-domain/src/main/java/kr/mashup/branding/domain/danggn/Exception/DanggnRankingRoundNotFoundException.java
- mashup-domain/src/main/java/kr/mashup/branding/repository/danggn/DanggnNotificationMemberRecordRepository.java
- mashup-domain/src/main/java/kr/mashup/branding/repository/danggn/DanggnNotificationPlatformRecordRepository.java
- mashup-domain/src/main/java/kr/mashup/branding/repository/danggn/DanggnRankingRewardRepository.java
- mashup-domain/src/main/java/kr/mashup/branding/repository/danggn/DanggnRankingRoundRepository.java
- mashup-domain/src/main/java/kr/mashup/branding/repository/danggn/DanggnRankingRoundRepositoryCustom.java
- mashup-domain/src/main/java/kr/mashup/branding/repository/danggn/DanggnRankingRoundRepositoryCustomImpl.java
- mashup-domain/src/main/java/kr/mashup/branding/repository/danggn/DanggnScoreRepository.java
- mashup-domain/src/main/java/kr/mashup/branding/repository/danggn/DanggnScoreRepositoryCustom.java
- mashup-domain/src/main/java/kr/mashup/branding/repository/danggn/DanggnScoreRepositoryCustomImpl.java
- mashup-domain/src/main/java/kr/mashup/branding/service/danggn/DanggnCacheService.java
- mashup-domain/src/main/java/kr/mashup/branding/service/danggn/DanggnNotificationRecordService.java
- mashup-domain/src/main/java/kr/mashup/branding/service/danggn/DanggnRankingRewardService.java
- mashup-domain/src/main/java/kr/mashup/branding/service/danggn/DanggnRankingRewardStatus.java
- mashup-domain/src/main/java/kr/mashup/branding/service/danggn/DanggnRankingRoundService.java
- mashup-domain/src/main/java/kr/mashup/branding/service/danggn/DanggnScoreService.java
- mashup-domain/src/main/java/kr/mashup/branding/util/DateUtil.java
- mashup-member/src/main/java/kr/mashup/branding/facade/danggn/DanggnFacadeService.java
- mashup-member/src/main/java/kr/mashup/branding/facade/danggn/DanggnNotiFacadeService.java
- mashup-member/src/main/java/kr/mashup/branding/ui/danggn/DanggnController.java
- mashup-member/src/main/java/kr/mashup/branding/ui/danggn/response/DanggnRankingRoundResponse.java
- mashup-member/src/main/java/kr/mashup/branding/ui/danggn/response/DanggnRankingRoundsResponse.java
- 당근 랭킹 회차 단건 API 작업
- 예시 응답값  
```json
{
"code": "SUCCESS",
"message": "성공",
"data": {
"number": 2,
"startDate": "2023-06-18",
"endDate": "2023-06-20",
"dateCount": 2,
"danggnRankingReward": {
"id": 1,
"name": "호선우",
"comment": null,
"status": "FIRST_PLACE_MEMBER_NOT_REGISTERED"
}
}
}
```
- 당근 랭킹 회차 다건 API 작업
- 예시 응답값
```json
{
"code": "SUCCESS",
"message": "성공",
"data": {
"danggnRankingRounds": [
{
"id": 2,
"number": 2,
"startDate": "2023-06-18",
"endDate": "2023-06-20"
},
{
"id": 1,
"number": 1,
"startDate": "2023-06-18",
"endDate": "2023-06-18"
}
]
}
}
```
- danggn_score, danggn_notification_member_record, danggn_notification_platform_record 테이블에 danggn_ranking_round_id 필드 추가
- 당근 랭킹 조회 API는 파라미터로 danggnRankingRoundId 넘겨주지 않으면 현재 운영중인 회차 기준으로 조회
- 당근 점수 추가 API는 danggnRankingRoundId를 …
> feat: 당근 랭킹 회차 API 작업

- mashup-domain/src/main/java/kr/mashup/branding/service/danggn/DanggnRankingRoundService.java
- mashup-domain/src/main/java/kr/mashup/branding/service/popup/MemberPopupService.java
- mashup-member/src/main/java/kr/mashup/branding/facade/popup/MemberPopupFacadeService.java
- 당근 1등 리워드 팝업의 경우, 최근 1등인 경우에만 노출하도록 수정
> fix: 당근 1등 리워드 팝업의 경우, 최근 1등인 경우에만 노출

- mashup-domain/src/main/java/kr/mashup/branding/domain/member/MemberGeneration.java
- mashup-domain/src/main/java/kr/mashup/branding/domain/member/MemberProfile.java
- mashup-domain/src/main/java/kr/mashup/branding/domain/scorehistory/ScoreHistory.java
- mashup-domain/src/main/java/kr/mashup/branding/repository/member/MemberProfileRepository.java
- mashup-domain/src/main/java/kr/mashup/branding/service/member/MemberProfileService.java
- mashup-domain/src/main/java/kr/mashup/branding/service/member/MemberService.java
- mashup-member/src/main/java/kr/mashup/branding/facade/member/MemberFacadeService.java
- mashup-member/src/main/java/kr/mashup/branding/facade/member/MemberProfileFacadeService.java
- mashup-member/src/main/java/kr/mashup/branding/ui/member/MemberController.java
- mashup-member/src/main/java/kr/mashup/branding/ui/member/MemberGenerationController.java
- mashup-member/src/main/java/kr/mashup/branding/ui/member/MemberProfileController.java
- mashup-member/src/main/java/kr/mashup/branding/ui/member/request/MemberGenerationRequest.java
- mashup-member/src/main/java/kr/mashup/branding/ui/member/request/MemberProfileRequest.java
- mashup-member/src/main/java/kr/mashup/branding/ui/member/response/MemberGenerationResponse.java
- mashup-member/src/main/java/kr/mashup/branding/ui/member/response/MemberGenerationsResponse.java
- mashup-member/src/main/java/kr/mashup/branding/ui/member/response/MemberProfileResponse.java
- 멤버 프로필 조회 및 업데이트 API 추가
- 멤버 기수 정보 조회 및 업데이트 API 추가
fyi; [피그마 링크](https://www.figma.com/file/kxgTs6r19oJz6ipQGYm83d/%EB%A7%A4%EC%89%AC%EC%97%85-%EC%95%B1?type=design&node-id=2-7&mode=design)
> feat: 멤버 프로필 및 기수 정보 관련 API 추가

- mashup-member/src/main/java/kr/mashup/branding/facade/attendance/AttendanceFacadeService.java
- mashup-member/src/main/java/kr/mashup/branding/facade/member/MemberProfileFacadeService.java
- mashup-member/src/main/java/kr/mashup/branding/facade/scorehistory/ScoreHistoryFacadeService.java
- mashup-member/src/main/java/kr/mashup/branding/ui/attendance/response/PlatformAttendanceResponse.java
- mashup-member/src/main/java/kr/mashup/branding/ui/member/MemberGenerationController.java
- mashup-member/src/main/java/kr/mashup/branding/ui/member/MemberProfileController.java
- mashup-member/src/main/java/kr/mashup/branding/ui/member/response/MemberProfileResponse.java
- mashup-member/src/main/java/kr/mashup/branding/ui/scorehistory/ScoreHistoryController.java
- 출결 조회 API 응답값에 멤버 프로필 조회에 필요한 멤버 아이디 추가
- 멤버 프로필 조회 API 추가
- 멤버 점수 조회 API 추가
> 멤버 프로필 조회 API 추가

- mashup-admin/src/main/java/kr/mashup/branding/facade/schedule/ScheduleFacadeService.java
- mashup-admin/src/main/java/kr/mashup/branding/ui/schedule/request/ScheduleCreateRequest.java
- mashup-admin/src/main/java/kr/mashup/branding/ui/schedule/request/ScheduleUpdateRequest.java
- mashup-admin/src/main/java/kr/mashup/branding/ui/schedule/response/ScheduleResponse.java
- mashup-domain/src/main/java/kr/mashup/branding/domain/schedule/Location.java
- mashup-domain/src/main/java/kr/mashup/branding/domain/schedule/Schedule.java
- mashup-domain/src/main/java/kr/mashup/branding/domain/schedule/ScheduleCreateDto.java
- mashup-domain/src/main/java/kr/mashup/branding/service/schedule/ScheduleService.java
- mashup-member/src/main/java/kr/mashup/branding/ui/schedule/response/ScheduleResponse.java
- 어드민 스케줄 생성/수정에 위치 정보 추가
- 어드민/멤버 스케줄 조회에 위치 정보 추가
- 어드민/멤버 `ScheduleResponse`에 위도 경도 추가
- 어드민 `ScheduleUpdateRequest`에 위도 경도 추가
- 어드민 `ScheduleCreateRequest`에 위도 경도 추가
> 스케줄에 위치 정보 추가

- mashup-domain/src/main/java/kr/mashup/branding/domain/mashong/MashongMission.java
> MashongMission에서 다음 미션 레벨 얻어올 때 없으면 null이 아니라 max 값을 반환하게 수정

- mashup-admin/src/main/java/kr/mashup/branding/ui/pushnoti/PushNotiEventListener.java
- mashup-domain/build.gradle
- mashup-domain/src/main/java/kr/mashup/branding/infrastructure/pushnoti/FcmPushNotiService.java
- FCM 에서 서비스 중단한 API라서 동일한 기능을 하는 다른 API 로 변경(푸시 알림 발송 시에 에러 로그가 발생하고 알림 발송이 되지 않음)
> feat: fcm deprecated api 대응

- mashup-domain/src/main/java/kr/mashup/branding/repository/member/MemberGenerationRepositoryCustom.java
- mashup-domain/src/main/java/kr/mashup/branding/repository/member/MemberGenerationRepositoryCustomImpl.java
- mashup-domain/src/main/java/kr/mashup/branding/service/member/MemberService.java
- mashup-member/src/main/java/kr/mashup/branding/config/web/MemberAuthArgumentResolver.java
- mashup-member/src/main/java/kr/mashup/branding/facade/birthday/BirthdayCardFacadeService.java
- mashup-member/src/main/java/kr/mashup/branding/facade/member/MemberFacadeService.java
- mashup-member/src/main/java/kr/mashup/branding/security/JwtService.java
- mashup-member/src/main/java/kr/mashup/branding/ui/member/MemberController.java
- 토큰 페이로드에서 멤버의 최신 기수 제거(다음 기수를 이어서 하는 멤버의 경우, 토큰이 발급된 시점의 기수와 그 다음 기수가 맞지 않아서 기수 재시작시에 재로그인이 필요한 불편함이 있음)
- MemberAuth 객체의 멤버의 최신 기수 필드는 조회하여 가져오도록 수정
> feat: 멤버의 최신 기수를 조회하여 가져오도록 수정

- mashup-domain/src/main/java/kr/mashup/branding/domain/scorehistory/ScoreType.java
- mashup-domain/src/main/java/kr/mashup/branding/service/scorehistory/ScoreHistoryService.java
- mashup-member/src/main/java/kr/mashup/branding/facade/member/MemberFacadeService.java
```
1. 출석(1점): 모두 출석한 경우
2. 지각(0.5): 모두 출석 했으나 첫번째 체크가 10분~30분 늦게 찍힌 경우
3. 결석(0점): 하나라도 출석이 안되었거나, 첫번째 체크가 30분 이후인 경우
4. 2점짜리의 세미나는 2일로 나누어 오픈하고, 위와 동일한 룰을 따름
```
> feat: 변경된 출석 점수 반영
