mash-up-kr/mashup-server

mashup-api/build.gradle, mashup-api/src/main/java/kr/mashup/branding/infrastructure/data/TestDataInitializer.java, mashup-api/src/main/java/kr/mashup/branding/ui/application/form/ApplicationFormAssembler.java, mashup-api/src/main/java/kr/mashup/branding/ui/application/form/ApplicationFormResponse.java, mashup-api/src/main/java/kr/mashup/branding/ui/application/form/QuestionResponse.java, mashup-api/src/main/java/kr/mashup/branding/ui/team/TeamAssembler.java, mashup-api/src/main/java/kr/mashup/branding/ui/team/TeamResponse.java, mashup-domain/src/main/java/kr/mashup/branding/domain/application/form/CreateApplicationFormVo.java, mashup-domain/src/main/java/kr/mashup/branding/domain/application/form/CreateQuestionVo.java, mashup-domain/src/main/java/kr/mashup/branding/domain/team/CreateTeamVo.java
- db mysql 로 변경되기 전까지, 어플리케이션 시작시에 기본 데이터 추가
=> local, develop 환경에서 테스트 데이터 추가

mashup-api/src/main/java/kr/mashup/branding/ui/application/AnswerRequest.java, mashup-api/src/main/java/kr/mashup/branding/ui/application/AnswerResponse.java, mashup-api/src/main/java/kr/mashup/branding/ui/application/ApplicationAssembler.java, mashup-api/src/main/java/kr/mashup/branding/ui/application/ApplicationResponse.java, mashup-api/src/main/java/kr/mashup/branding/ui/application/CreateApplicationRequest.java, mashup-api/src/main/java/kr/mashup/branding/ui/application/UpdateApplicationRequest.java, mashup-domain/src/main/java/kr/mashup/branding/domain/application/AnswerRequestVo.java, mashup-domain/src/main/java/kr/mashup/branding/domain/application/Application.java
- `@Data` 어노테이션과 final 필드 조합해서 사용하면 api 요청시 실패하는 현상 해결
- api 응답에 필요한 필드 추가
=> 지원서 조회, 생성, 임시저장, 제출 api 개선

mashup-api/src/main/java/kr/mashup/branding/infrastructure/data/TestDataInitializer.java, mashup-api/src/main/java/kr/mashup/branding/ui/application/form/ApplicationFormAssembler.java, mashup-api/src/main/java/kr/mashup/branding/ui/application/form/ApplicationFormResponse.java, mashup-api/src/main/java/kr/mashup/branding/ui/application/form/QuestionResponse.java, mashup-domain/src/main/java/kr/mashup/branding/domain/application/form/ApplicationForm.java, mashup-domain/src/main/java/kr/mashup/branding/domain/application/form/ApplicationFormServiceImpl.java, mashup-domain/src/main/java/kr/mashup/branding/domain/application/form/CreateApplicationFormVo.java, mashup-domain/src/main/java/kr/mashup/branding/domain/application/form/CreateQuestionVo.java, mashup-domain/src/main/java/kr/mashup/branding/domain/application/form/Question.java, mashup-domain/src/main/java/kr/mashup/branding/domain/application/form/QuestionType.java
- 지원서 이름
- 질문 종류 (단답형, 장문형)
- 질문 필수 여부
=> 지원서, 질문 필드 추가

mashup-admin/src/main/java/kr/mashup/branding/facade/team/TeamFacadeService.java, mashup-admin/src/main/java/kr/mashup/branding/facade/team/TeamFacadeServiceImpl.java, mashup-admin/src/main/java/kr/mashup/branding/ui/team/CreateTeamRequest.java, mashup-admin/src/main/java/kr/mashup/branding/ui/team/TeamAssembler.java, mashup-admin/src/main/java/kr/mashup/branding/ui/team/TeamController.java, mashup-admin/src/main/java/kr/mashup/branding/ui/team/TeamResponse.java, mashup-api/src/main/java/kr/mashup/branding/infrastructure/data/TestDataInitializer.java, mashup-domain/src/main/java/kr/mashup/branding/domain/team/TeamService.java, mashup-domain/src/main/java/kr/mashup/branding/domain/team/TeamServiceImpl.java
- createdBy, updatedBy 는 로그인 기능 완료되면 추가 예정
=> feat: 팀 생성, 조회

mashup-domain/build.gradle
- querydsl 사용하는 예제 코드는 따로 추가하겠습니다. 로컬환경에서 동작하는건 확인했었어요
=> config: querydsl 의존성 추가

mashup-api/src/main/java/kr/mashup/branding/ui/ApiControllerAdvice.java, mashup-api/src/main/java/kr/mashup/branding/ui/application/ApplicationAssembler.java, mashup-api/src/main/java/kr/mashup/branding/ui/application/ApplicationResponse.java, mashup-api/src/main/java/kr/mashup/branding/ui/application/UpdateApplicationRequest.java, mashup-domain/src/main/java/kr/mashup/branding/domain/MashupScheduleService.java, mashup-domain/src/main/java/kr/mashup/branding/domain/application/Application.java, mashup-domain/src/main/java/kr/mashup/branding/domain/application/ApplicationServiceImpl.java, mashup-domain/src/main/java/kr/mashup/branding/domain/application/PrivacyPolicyNotAgreedException.java, mashup-domain/src/main/java/kr/mashup/branding/domain/application/UpdateApplicationVo.java, mashup-domain/src/main/java/kr/mashup/branding/domain/application/result/ApplicationResult.java, mashup-domain/src/test/java/kr/mashup/branding/domain/application/ApplicationTest.java
- `privacyPolicyAgreed` 필드 추가
- 임시저장, 제출시 개인정보 처리방침에 동의한 상태가 아니면 exception 발생
- 테스트케이스 추가
=> feat: 개인정보 처리방침 동의여부 추가

mashup-api/build.gradle, mashup-api/src/main/java/kr/mashup/branding/config/jwt/JwtService.java, mashup-api/src/main/java/kr/mashup/branding/config/security/PreAuthTokenProvider.java, mashup-api/src/main/java/kr/mashup/branding/config/security/SecurityConfig.java, mashup-api/src/main/java/kr/mashup/branding/config/security/TokenMissingException.java, mashup-api/src/main/java/kr/mashup/branding/config/security/TokenPreAuthFilter.java, mashup-api/src/main/java/kr/mashup/branding/facade/login/LoginFacadeService.java, mashup-api/src/main/java/kr/mashup/branding/facade/login/LoginFacadeServiceImpl.java, mashup-api/src/main/java/kr/mashup/branding/ui/applicant/ApplicantAssembler.java, mashup-api/src/main/java/kr/mashup/branding/ui/applicant/ApplicantController.java, mashup-api/src/main/java/kr/mashup/branding/ui/applicant/LoginRequest.java, mashup-api/src/main/java/kr/mashup/branding/ui/applicant/LoginResponse.java, mashup-api/src/main/resources/application.yml, mashup-api/src/test/resources/application.yml, mashup-domain/src/main/java/kr/mashup/branding/domain/applicant/Applicant.java, mashup-domain/src/main/java/kr/mashup/branding/domain/applicant/ApplicantRepository.java, mashup-domain/src/main/java/kr/mashup/branding/domain/applicant/ApplicantService.java, mashup-domain/src/main/java/kr/mashup/branding/domain/applicant/ApplicantServiceImpl.java, mashup-domain/src/main/java/kr/mashup/branding/domain/applicant/LoginRequestVo.java, mashup-domain/src/main/java/kr/mashup/branding/domain/applicant/LoginResponseVo.java, mashup-domain/src/main/resources/application-local.yml
- spring security 적용
- login 응답으로 jwt token 반환
- postman으로 테스트 진행
=> feat: applicant login

mashup-admin/src/main/java/kr/mashup/branding/facade/adminmember/AdminMemberFacadeService.java, mashup-admin/src/main/java/kr/mashup/branding/facade/adminmember/AdminMemberFacadeServiceImpl.java, mashup-admin/src/main/java/kr/mashup/branding/ui/adminmember/AdminMemberController.java, mashup-batch/build.gradle, mashup-batch/src/main/java/kr/mashup/branding/MashupBatchApplication.java, mashup-batch/src/main/java/kr/mashup/branding/config/BatchConfig.java, mashup-batch/src/main/java/kr/mashup/branding/signup/AdminMemberSignUpJobConfig.java, mashup-batch/src/main/java/kr/mashup/branding/signup/AdminMemberSignupTasklet.java, mashup-domain/build.gradle, mashup-domain/src/main/java/kr/mashup/branding/config/PasswordEncoderConfig.java, mashup-domain/src/main/java/kr/mashup/branding/domain/adminmember/AdminMemberRepository.java, mashup-domain/src/main/java/kr/mashup/branding/domain/adminmember/AdminMemberServiceImpl.java, mashup-domain/src/main/java/kr/mashup/branding/domain/adminmember/AdminMemberSignUpRequestInvalidException.java, mashup-domain/src/main/java/kr/mashup/branding/domain/adminmember/AdminMemberUsernameDuplicatedException.java, settings.gradle
- 배치 모듈 추가
- 회원가입 배치 추가
- 회원가입 API 삭제
- 가입시 validation, password encoding 로직 추가
=> feat: admin 회원가입 배치 추가

mashup-admin/src/main/java/kr/mashup/branding/ui/application/ApplicationController.java, mashup-admin/src/main/java/kr/mashup/branding/ui/application/form/ApplicationFormController.java, mashup-admin/src/main/java/kr/mashup/branding/ui/team/TeamController.java, mashup-api/src/main/java/kr/mashup/branding/ui/application/form/ApplicationFormController.java
- 이전에 작성한 api 중에 공통 dto 사용하지 않고있는 코드 찾아서 수정
=> feat: 공통 dto 적용 (api, admin)

mashup-admin/src/main/java/kr/mashup/branding/facade/adminmember/AdminMemberFacadeService.java, mashup-admin/src/main/java/kr/mashup/branding/facade/adminmember/AdminMemberFacadeServiceImpl.java, mashup-admin/src/main/java/kr/mashup/branding/facade/adminmember/LoginResponseVo.java, mashup-admin/src/main/java/kr/mashup/branding/ui/adminmember/AdminMemberAssembler.java, mashup-admin/src/main/java/kr/mashup/branding/ui/adminmember/AdminMemberController.java, mashup-admin/src/main/java/kr/mashup/branding/ui/adminmember/AdminMemberResponse.java, mashup-admin/src/main/java/kr/mashup/branding/ui/adminmember/LoginRequest.java, mashup-admin/src/main/java/kr/mashup/branding/ui/adminmember/LoginResponse.java, mashup-admin/src/main/java/kr/mashup/branding/ui/adminmember/SignInResponse.java, mashup-domain/src/main/java/kr/mashup/branding/domain/adminmember/AdminMemberLoginVo.java, mashup-domain/src/main/java/kr/mashup/branding/domain/adminmember/AdminMemberService.java, mashup-domain/src/main/java/kr/mashup/branding/domain/adminmember/AdminMemberServiceImpl.java
=> feat: sign-in -> login 으로 변경

mashup-admin/src/main/java/kr/mashup/branding/ui/application/ApplicationAssembler.java, mashup-admin/src/main/java/kr/mashup/branding/ui/application/ApplicationDetailResponse.java, mashup-admin/src/main/java/kr/mashup/branding/ui/application/ApplicationSimpleResponse.java
=> feat: admin 설문지 응답 개선

mashup-api/src/main/resources/api-develop.yml, mashup-api/src/main/resources/api-local.yml
- google client id 브랜딩 계정으로 변경
=> fix: google client id 변경

mashup-domain/src/main/java/kr/mashup/branding/domain/application/Application.java, mashup-domain/src/main/java/kr/mashup/branding/domain/application/confirmation/Confirmation.java
=> fix: 지원서쪽 연관관계 수정

mashup-api/src/main/java/kr/mashup/branding/facade/application/ApplicationFacadeService.java, mashup-api/src/main/java/kr/mashup/branding/facade/application/ApplicationFacadeServiceImpl.java, mashup-api/src/main/java/kr/mashup/branding/ui/application/AnswerRequest.java, mashup-api/src/main/java/kr/mashup/branding/ui/application/ApplicationAssembler.java, mashup-api/src/main/java/kr/mashup/branding/ui/application/ApplicationController.java, mashup-api/src/main/java/kr/mashup/branding/ui/application/ApplicationSubmitRequest.java, mashup-domain/src/main/java/kr/mashup/branding/domain/ResultCode.java, mashup-domain/src/main/java/kr/mashup/branding/domain/applicant/Applicant.java, mashup-domain/src/main/java/kr/mashup/branding/domain/application/Answer.java, mashup-domain/src/main/java/kr/mashup/branding/domain/application/AnswerRequestVo.java, mashup-domain/src/main/java/kr/mashup/branding/domain/application/Application.java, mashup-domain/src/main/java/kr/mashup/branding/domain/application/ApplicationService.java, mashup-domain/src/main/java/kr/mashup/branding/domain/application/ApplicationServiceImpl.java, mashup-domain/src/main/java/kr/mashup/branding/domain/application/ApplicationStatus.java, mashup-domain/src/main/java/kr/mashup/branding/domain/application/ApplicationSubmitRequestInvalidException.java, mashup-domain/src/main/java/kr/mashup/branding/domain/application/ApplicationSubmitRequestVo.java, mashup-domain/src/main/java/kr/mashup/branding/domain/application/form/ApplicationFormServiceImpl.java, mashup-domain/src/main/java/kr/mashup/branding/infrastructure/data/TestDataInitializer.java, mashup-domain/src/test/java/kr/mashup/branding/domain/application/ApplicationTest.java
임시저장: 개인정보처리방침 검증
제출 : 지원서 상태만 변경
임시저장: 아무것도 검증하지않고 저장만함
제출: 임시저장시 사용하는 모든 필드 body 에 추가, 검증로직 추가
=> feat: 지원서 제출시 지원서 내용 입력, 검증하도록 변경

mashup-api/src/main/java/kr/mashup/branding/ui/application/ApplicationAssembler.java, mashup-api/src/main/java/kr/mashup/branding/ui/application/ApplicationStatusResponse.java
- 임시저장 상태에서 서류 마감기한까지 제출하지 않은 경우, 지원내역에서 `기한 만료`라고 보여준다
=> feat: 기한 만료 상태 추가

mashup-domain/src/main/java/kr/mashup/branding/domain/application/ApplicationRepositoryImpl.java, mashup-domain/src/main/java/kr/mashup/branding/domain/application/form/ApplicationFormRepositoryImpl.java, mashup-domain/src/main/java/kr/mashup/branding/util/QueryUtils.java
* 페이지네이션에서 데이터 중복 현상 및 totalCount가 잘못 나오는 이슈 수정
=> fix: 페이지네이션 이슈 수정

docker-compose.yml, mashup-admin/Dockerfile, mashup-admin/src/main/resources/admin.yml, mashup-domain/src/main/resources/application-develop.yml, mashup-domain/src/main/resources/application-local.yml, mashup-domain/src/main/resources/application-production.yml
- 어드민 서버 포트 8090으로 변경, API 서버는 8080 사용
- local, develop, production 필요한 환경 변수 암호화하여 변경
=> config: 서버 migration 관련 환경 설정 변경

.github/CODEOWNERS, docker-compose.yml, mashup-admin/src/main/resources/admin-develop.yml, mashup-admin/src/main/resources/admin-local.yml, mashup-admin/src/main/resources/admin-production.yml, mashup-api/src/main/resources/api-develop.yml, mashup-api/src/main/resources/api-local.yml, mashup-api/src/main/resources/api-production.yml, mashup-domain/src/main/resources/logback/logback-spring.xml
- 파일 appender 설정
- docker-compose 사용할 설정 정리
=> config: logback 및 docker-compose 설정 추가

mashup-admin/src/main/resources/admin-develop.yml, mashup-admin/src/main/resources/admin-local.yml, mashup-admin/src/main/resources/admin-production.yml, mashup-api/src/main/java/kr/mashup/branding/ui/ApiControllerAdvice.java, mashup-api/src/main/java/kr/mashup/branding/ui/applicant/ApplicantAssembler.java, mashup-api/src/main/java/kr/mashup/branding/ui/applicant/ApplicantResponse.java, mashup-api/src/main/java/kr/mashup/branding/ui/application/ApplicationAssembler.java, mashup-api/src/main/java/kr/mashup/branding/ui/application/ApplicationSubmitRequest.java, mashup-api/src/main/java/kr/mashup/branding/ui/application/UpdateApplicationRequest.java, mashup-api/src/main/resources/api-develop.yml, mashup-api/src/main/resources/api-local.yml, mashup-api/src/main/resources/api-production.yml, mashup-domain/src/main/java/kr/mashup/branding/domain/applicant/Applicant.java, mashup-domain/src/main/java/kr/mashup/branding/domain/application/Application.java, mashup-domain/src/main/java/kr/mashup/branding/domain/application/ApplicationSubmitRequestVo.java, mashup-domain/src/main/java/kr/mashup/branding/domain/application/UpdateApplicationVo.java, mashup-domain/src/main/java/kr/mashup/branding/infrastructure/data/TestDataInitializer.java, mashup-domain/src/main/resources/logback/logback-spring.xml
=> feat: 지원자의 필요한 개인정보 추가

.github/workflows/deploy-dev-admin.yml
=> chore: create admin dev cicd script

.github/workflows/deploy-dev-api.yml
=> chore: dev api cicd yml 생성

mashup-api/Dockerfile
=> chore: dockerfile 수정

mashup-admin/Dockerfile, mashup-api/Dockerfile
=> fix: reset dockerfile

.github/workflows/deploy-dev-admin.yml, mashup-admin/Dockerfile
=> feat: 어드민 서버 CI/CD

mashup-api/Dockerfile
=> fix: 경로 수정

mashup-admin/src/main/java/kr/mashup/branding/ui/application/ApplicationResultStatus.java, mashup-domain/src/main/java/kr/mashup/branding/domain/application/result/ApplicationResult.java
* SCREENING_FAILED로 지원서 수정하여도 PASSED로 나오는 이슈 수정
* 면접 시작과 종료 시간을 주어도 적용되지 않은 이슈 수정
=> fix: 지원서 상태 업데이트 시 이슈 수정

mashup-domain/src/main/resources/application-production.yml
=> chore: 시크릿 값에 닫는가로 추가

mashup-admin/src/main/java/kr/mashup/branding/ui/adminmember/AdminMemberAssembler.java, mashup-admin/src/main/java/kr/mashup/branding/ui/adminmember/AdminMemberResponse.java
* admin-members/me API에 핸드폰 정보 필드 추가
=> feat: admin-members​/me API에 핸드폰 정보 추가

mashup-admin/src/main/java/kr/mashup/branding/ui/application/ApplicationAssembler.java, mashup-admin/src/main/java/kr/mashup/branding/ui/application/ApplicationSimpleResponse.java, mashup-domain/src/main/java/kr/mashup/branding/domain/application/ApplicationRepositoryImpl.java
- submittedAt 필드 추가
- 지원 일시를 기준으로 역순 정렬
=> feat: admin 지원서 목록 보기 API 수정

mashup-admin/src/main/java/kr/mashup/branding/config/messageconverter/HTMLCharacterEscapes.java, mashup-api/src/main/java/kr/mashup/branding/config/messageconverter/HTMLCharacterEscapes.java
- escapeHtml4 -> escapeHtml3 (HTML4.0 extended escape 제거)
=> fix: escape 문자 타입 변경

mashup-domain/src/main/java/kr/mashup/branding/domain/application/ApplicationRepositoryImpl.java
* 서류 합격인 지원서 조회 시 최종 합격 지원서까지 나오는 이슈 해결
* <img width="1304" alt="image" src="https://user-images.githubusercontent.com/26344479/160668588-c4c8365a-c343-4996-81e2-f182b3fda670.png">
=> fix: 서류 합격인 지원서 조회 시 최종 합격 지원서도 나오는 이슈 해결

mashup-domain/src/main/java/kr/mashup/branding/domain/notification/NotificationServiceImpl.java
* 문자 발송 목록 기본 정렬을 최근순으로 수정
* QA 내역
* https://www.notion.so/0328-QA-93ca8b59b60d4b14a056046b7c89bf45?p=b4a8c16efca5466785d5171575722b58
=> feat: 문자 발송 목록 조회 시 기본은 최근순으로 수정

mashup-admin/src/main/java/kr/mashup/branding/ui/application/ApplicationAssembler.java
=> feat: 상세 내역에서 sms는 최신순

mashup-domain/src/main/java/kr/mashup/branding/domain/scoreHistory/ScoreHistory.java, mashup-domain/src/main/java/kr/mashup/branding/domain/scoreHistory/Title.java
- 논의한 내용 바탕으로 생성하였습니다.
```
public enum Title {
ATTENDANCE("출석"),
ABSENT("결석"),
LATE("지각"),
DEPLOY_FAIL("프로젝트 배포 실패"),
DEPLOY_SUCCESS("프로젝트 배포 성공"),
SEMINAR_PRESENTATION("전체 세미나 발표"),
PROJECT_LEADER("프로젝트팀 팀장"),
PROJECT_SUBLEADER("프로젝트 부팀장"),
HACKATHON_COMMITTEE("해커톤 준비 위원회"),
TECH_BLOG_WRITE("기술블로그 작성"),
MASHUP_CONTENT_WRITE("Mah-Up 콘텐츠 글 작성"),
MASHUP_LEADER("13기 회장"),
MASHUP_SUBLEADER("13기 부회장"),
;
Title(String description) {
}
}
```
- [피그마](https://www.figma.com/file/BILwN4haBYn9XNtoFJZyom?node-id=411:1387#224632904)에 명시된 내용 바탕으로 생성하였습니다.
⭐️코드 리뷰 감사합니당⭐️
=> feat: 출석 히스토리 엔티티 생성

mashup-batch/src/main/java/kr/mashup/branding/scorehistory/ScoreHistoryConfig.java, mashup-domain/src/main/java/kr/mashup/branding/repository/member/MemberRepository.java, mashup-domain/src/main/java/kr/mashup/branding/repository/schedule/ScheduleRepository.java, mashup-domain/src/main/java/kr/mashup/branding/service/scorehistory/ScoreHistoryService.java
=> feat: score history 배치 구현

mashup-member/src/main/java/kr/mashup/branding/ui/attendance/AttendanceController.java, mashup-member/src/main/java/kr/mashup/branding/ui/qrcode/QrCodeController.java
- 텍스트 블록 방식에서 기존 문자열 조합 방식으로 변경
=> hotfix: 문자열 조합 방식으로 변경

mashup-admin/src/main/java/kr/mashup/branding/ui/schedule/response/ContentResponse.java, mashup-domain/src/main/java/kr/mashup/branding/domain/schedule/Content.java, mashup-domain/src/main/java/kr/mashup/branding/domain/schedule/ContentsCreateDto.java, mashup-domain/src/main/java/kr/mashup/branding/service/schedule/ScheduleService.java, mashup-member/src/main/java/kr/mashup/branding/ui/schedule/response/ContentResponse.java
* 컬럼중 desc로 이름이 되어 있어서 MySQL에서 에러(예약어라서 그런듯;)
* desc -> description 으로 수정
=> fix: 컨텐츠 컬럼 이름수정

mashup-domain/src/main/java/kr/mashup/branding/infrastructure/test/NoopApplicationScheduleValidator.java
=> fix: 데브에서도 지원서 기간 검증으로 수정

mashup-member/src/main/java/kr/mashup/branding/ui/member/response/AccessResponse.java
=> feat: 로그인, 회원가입 응답값에 푸시 알림 동의 여부 필드 추가

mashup-batch/build.gradle, mashup-batch/src/main/java/kr/mashup/branding/scorehistory/ScoreHistoryScheduler.java, mashup-batch/src/main/resources/logback/logback-spring.xml
=> 점수 계산 배치 오류 수정

mashup-batch/src/main/java/kr/mashup/branding/facade/InterviewGuideLinkFacadeService.java, mashup-domain/src/main/java/kr/mashup/branding/service/application/ApplicationService.java
* 전체 플랫폼으로 인터뷰 링크 설정 배치를 돌릴 시에 오류 수정
=> 전체 플랫폼 돌릴 시 오류 수정

mashup-admin/src/main/java/kr/mashup/branding/facade/schedule/ScheduleFacadeService.java, mashup-admin/src/main/java/kr/mashup/branding/ui/schedule/ScheduleController.java, mashup-domain/src/main/java/kr/mashup/branding/domain/schedule/Schedule.java
=> 스케줄 업데이트 오류 수정

mashup-admin/src/main/java/kr/mashup/branding/facade/schedule/ScheduleFacadeService.java, mashup-admin/src/main/java/kr/mashup/branding/ui/schedule/response/EventResponse.java, mashup-domain/src/main/java/kr/mashup/branding/domain/schedule/Event.java, mashup-domain/src/main/java/kr/mashup/branding/domain/schedule/Schedule.java, mashup-domain/src/main/java/kr/mashup/branding/service/schedule/ScheduleService.java
- Schedule에 changeDate 추가
- 스케줄 업데이트 로직 추가
=> 스케줄 날짜 업데이트 에러 수정

mashup-recruit/src/main/java/kr/mashup/branding/ui/scheduler/ConfirmationScheduler.java
- 핫픽스
- 최종 승낙 시간을 변경한다.
- 최종 승낙 스케줄러 시간 변경
=> [HOT-FIX] 최종 승낙 스케줄러 시간 수정

mashup-member/src/main/java/kr/mashup/branding/facade/schedule/ScheduleFacadeService.java
- 기능 수정
- 과거 지나간 기간은 음수로, 미래의 남은 기간은 양수로 계산하도록 수정하였습니다.
- 과거 지나간 기간은 음수로, 미래의 남은 기간은 양수로 계산하도록 수정하였습니다.
=> 미래의 날짜는 양수로 계산하도록 수정

mashup-domain/src/main/java/kr/mashup/branding/config/PasswordEncoderConfig.java, mashup-domain/src/main/java/kr/mashup/branding/service/member/MemberService.java, mashup-domain/src/main/java/lombok.config
수정
Password Encoder 속도로인해 round4 사용하도록 변경
=> add weak passwordencoder

mashup-member/src/main/java/kr/mashup/branding/facade/scorehistory/ScoreHistoryFacadeService.java
=> filter 로직 수정

mashup-domain/src/main/java/kr/mashup/branding/domain/member/Member.java, mashup-member/src/main/java/kr/mashup/branding/facade/scorehistory/ScoreHistoryFacadeService.java
=> fix filter logic

mashup-member/src/main/java/kr/mashup/branding/facade/scorehistory/ScoreHistoryFacadeService.java, mashup-member/src/main/java/kr/mashup/branding/ui/scorehistory/response/ScoreHistoryResponse.java
=> iscanceled

mashup-domain/src/main/java/kr/mashup/branding/domain/scorehistory/ScoreType.java, mashup-member/src/main/java/kr/mashup/branding/facade/member/MemberFacadeService.java
- 기능
- 기본 활동 점수(3점) 부여하는 로직 추가합니다.
- 회원가입 로직에 scoreHistory 저장 로직 추가
=> 기본 활동 점수 추가

mashup-member/src/main/java/kr/mashup/branding/facade/attendance/AttendanceFacadeService.java
=> fix LATE_LIMIT_TIME to 20 minutes

mashup-admin/src/main/java/kr/mashup/branding/facade/schedule/ScheduleFacadeService.java, mashup-domain/src/main/java/kr/mashup/branding/domain/schedule/Schedule.java
=> status로 배포시에만 보이게 수정

mashup-domain/src/main/java/kr/mashup/branding/repository/schedule/ScheduleRepository.java, mashup-domain/src/main/java/kr/mashup/branding/service/schedule/ScheduleService.java
=> 배포시에만 스케쥴보이게 수정

mashup-domain/src/main/java/kr/mashup/branding/domain/attendance/AttendanceCode.java, mashup-domain/src/main/java/kr/mashup/branding/repository/attendancecode/AttendanceCodeRepository.java, mashup-domain/src/main/java/kr/mashup/branding/service/attendance/AttendanceCodeService.java, mashup-member/src/main/java/kr/mashup/branding/facade/attendance/AttendanceFacadeService.java, mashup-member/src/main/java/kr/mashup/branding/ui/attendance/response/AttendanceCodeResponse.java
- 기능
- 기존 출석체크 컬럼명 변경 및 지각체크 컬럼 추가합니다.
- 확인하시면 컬럼 변경이랑 컬럼 추가합니다.
```
ALTER TABLE `attendance_code` RENAME COLUMN `started_at` TO `attendance_check_started_at`;
ALTER TABLE `attendance_code` RENAME COLUMN `ended_at` TO `attendance_check_ended_at`;
ALTER TABLE `attendance_code` ADD `lateness_check_ended_at` DATETIME(6) NOT NULL;
```
- 어드민에서 QR 생성하는 부분이랑 관련된 로직은 어드민 웹팀분께 여쭤보고 진행하겠습니다.
- 출석체크 컬럼명 변경 및 추가
- 출석체크 시작: attendanceCheckStartedAt(변경)
- 출석마감: attendanceCheckEndedAt(변경)
- 지각마감: latenessCheckEndedAt(추가)
- 상수값으로 지각 체크하던 로직을 지각마감 시간(추가된 컬럼)으로 대체
=> 출석체크 컬럼명 변경 및 추가

mashup-admin/src/main/java/kr/mashup/branding/facade/schedule/ScheduleFacadeService.java, mashup-admin/src/main/java/kr/mashup/branding/ui/schedule/request/QrCodeGenerateRequest.java, mashup-domain/src/main/java/kr/mashup/branding/domain/attendance/AttendanceCode.java, mashup-domain/src/main/java/kr/mashup/branding/util/DateRange.java
- 기능
- 지각 마감 시간 필드 추가해서 qr 생성합니다.
- DateRange에 mid 변수 추가
- 지각 마감 시간 필드 추가해서 qr 생성
=> 지각 시간 필드 추가해서 QR 코드 생성

mashup-member/src/main/java/kr/mashup/branding/facade/schedule/ScheduleFacadeService.java
=> feat: 음수 체크 조건 추가

mashup-member/src/main/java/kr/mashup/branding/facade/danggn/DanggnFacadeService.java, mashup-member/src/main/java/kr/mashup/branding/ui/danggn/DanggnController.java, mashup-member/src/main/java/kr/mashup/branding/ui/danggn/response/DanggnMemberRankData.java, mashup-member/src/main/java/kr/mashup/branding/ui/danggn/response/DanggnMemberRankResponse.java
=> limit 응답에 추가

mashup-domain/src/main/java/kr/mashup/branding/domain/danggn/DanggnTodayMessage.java, mashup-domain/src/main/java/kr/mashup/branding/repository/danggn/DanggnTodayMessageRepository.java, mashup-domain/src/main/java/kr/mashup/branding/service/danggn/DanggnTodayMessageService.java, mashup-member/src/main/java/kr/mashup/branding/facade/danggn/DanggnFacadeService.java, mashup-member/src/main/java/kr/mashup/branding/ui/danggn/DanggnController.java, mashup-member/src/main/java/kr/mashup/branding/ui/danggn/response/DanggnRandomMessageResponse.java
=> 랜덤 오늘의 메시지

mashup-domain/src/main/java/kr/mashup/branding/domain/member/Platform.java, mashup-domain/src/main/java/kr/mashup/branding/domain/pushnoti/vo/DanggnNotificationPlatformRecordUpdatedVo.java
- 기능
- 푸시 알림 플랫폼 알림에 필요한 문자열 추가
=> feat: 푸시 알림 플랫폼 문자열 추가

mashup-domain/src/main/resources/application-develop.yml, mashup-domain/src/main/resources/application-production.yml
=> feat: db 정보 수정

mashup-domain/src/main/java/kr/mashup/branding/domain/member/Member.java, mashup-domain/src/main/java/kr/mashup/branding/service/member/MemberService.java, mashup-member/src/main/java/kr/mashup/branding/facade/member/MemberFacadeService.java, mashup-member/src/main/java/kr/mashup/branding/ui/member/MemberController.java, mashup-member/src/main/java/kr/mashup/branding/ui/member/request/LoginRequest.java
=> fix: 비밀번호 찾기 기능 추가

mashup-domain/src/main/java/kr/mashup/branding/service/danggn/DanggnNotificationSentUnit.java
=> feat: 당근 누적 알림 단위 변경

mashup-domain/src/main/java/kr/mashup/branding/service/member/MemberService.java, mashup-member/src/main/java/kr/mashup/branding/ui/member/MemberController.java, mashup-member/src/main/java/kr/mashup/branding/ui/member/request/LoginRequest.java
=> fix: 비밀번호 변경 기능 삭제

mashup-admin/src/main/java/kr/mashup/branding/facade/member/MemberFacadeService.java, mashup-admin/src/main/java/kr/mashup/branding/ui/member/MemberController.java, mashup-admin/src/main/java/kr/mashup/branding/ui/member/request/MemberPasswordResetRequest.java
=> 비밀번호 초기화 기능

mashup-admin/src/main/java/kr/mashup/branding/facade/member/MemberFacadeService.java, mashup-admin/src/main/java/kr/mashup/branding/ui/member/MemberController.java
=> 회원 강제 탈퇴 기능

mashup-admin/src/main/java/kr/mashup/branding/facade/adminmember/AdminMemberFacadeService.java, mashup-admin/src/main/java/kr/mashup/branding/ui/adminmember/AdminMemberController.java, mashup-domain/src/main/java/kr/mashup/branding/service/adminmember/AdminMemberService.java
=> 어드민 멤버 생성, 리스트 조회 기능 추가

mashup-domain/src/main/java/kr/mashup/branding/domain/ResultCode.java, mashup-domain/src/main/java/kr/mashup/branding/domain/danggn/DanggnRankingReward.java, mashup-domain/src/main/java/kr/mashup/branding/domain/danggn/Exception/DanggnRankingRewardAlreadyWrittenException.java, mashup-domain/src/main/java/kr/mashup/branding/domain/danggn/Exception/DanggnRankingRewardNotAllowedException.java, mashup-domain/src/main/java/kr/mashup/branding/domain/danggn/Exception/DanggnRankingRewardNotFoundException.java, mashup-domain/src/main/java/kr/mashup/branding/domain/popup/PopupType.java, mashup-domain/src/main/java/kr/mashup/branding/repository/danggn/DanggnRankingRewardRepository.java, mashup-domain/src/main/java/kr/mashup/branding/repository/danggn/DanggnRankingRoundRepository.java, mashup-domain/src/main/java/kr/mashup/branding/service/danggn/DanggnRankingRewardService.java, mashup-domain/src/main/java/kr/mashup/branding/service/danggn/DanggnRankingRoundService.java, mashup-domain/src/main/java/kr/mashup/branding/service/popup/MemberPopupService.java, mashup-member/src/main/java/kr/mashup/branding/facade/danggn/DanggnFacadeService.java, mashup-member/src/main/java/kr/mashup/branding/facade/danggn/DanggnRankingSchedulerFacadeService.java, mashup-member/src/main/java/kr/mashup/branding/ui/danggn/DanggnController.java, mashup-member/src/main/java/kr/mashup/branding/ui/danggn/request/DanggnRankingRewardRequest.java
당근 리워드 코멘트 쓰기 api 및 validation
다음 회차 만들기
1등 업데이트
=> Danggn ranking 2

mashup-member/src/main/java/kr/mashup/branding/facade/danggn/DanggnFacadeService.java, mashup-member/src/main/java/kr/mashup/branding/ui/danggn/DanggnController.java, mashup-member/src/main/java/kr/mashup/branding/ui/danggn/response/DanggnRankingRoundResponse.java
- 당근 단건 회차 조회 시에, 해당 멤버가 1등인지 아닌지 판별하는 필드 추가
=> feat: 당근 단건 회차 조회 시, 1등 유무 필드 추가

mashup-admin/src/main/java/kr/mashup/branding/facade/storage/StorageFacadeService.java, mashup-admin/src/main/java/kr/mashup/branding/ui/storage/StorageController.java, mashup-admin/src/main/java/kr/mashup/branding/ui/storage/response/KeyResponse.java, mashup-domain/src/main/java/kr/mashup/branding/repository/storage/StorageRepository.java, mashup-domain/src/main/java/kr/mashup/branding/service/storage/StorageService.java
- 기능 추가
- key list 읽어오는 api 추가
- key list 읽어오는 api 추가
=> key list 읽어오는 api 추가

mashup-admin/src/main/java/kr/mashup/branding/facade/pushnoti/PushNotiFacadeService.java, mashup-domain/src/main/java/kr/mashup/branding/domain/pushnoti/LinkType.java, mashup-domain/src/main/java/kr/mashup/branding/domain/pushnoti/vo/DanggnRewardUpdatedVo.java, mashup-member/src/main/java/kr/mashup/branding/facade/danggn/DanggnFacadeService.java
- 1등 리워드 등록 푸시 알림 추가
- 푸시 알림 타입 추가 : DANGGN_REWARD
=> fix: 1등 리워드 등록 푸시 알림 추가

mashup-member/src/main/java/kr/mashup/branding/security/JwtService.java
- 기간이 만료된 토큰 UnauthorizedException 처리
=> fix: 기간이 만료된 토큰 UnauthorizedException 처리

mashup-admin/src/main/java/kr/mashup/branding/config/security/SecurityConfig.java, mashup-admin/src/main/java/kr/mashup/branding/ui/AdminControllerAdvice.java, mashup-admin/src/main/java/kr/mashup/branding/ui/adminmember/AdminMemberController.java
=> feat: 어드민 멤버 생성 권한 추가

mashup-admin/src/main/java/kr/mashup/branding/facade/adminmember/AdminMemberFacadeService.java, mashup-admin/src/main/java/kr/mashup/branding/ui/adminmember/AdminMemberController.java, mashup-admin/src/main/java/kr/mashup/branding/ui/adminmember/vo/AdminDeleteRequest.java, mashup-admin/src/main/java/kr/mashup/branding/ui/adminmember/vo/AdminPasswordChangeRequest.java, mashup-admin/src/main/java/kr/mashup/branding/ui/adminmember/vo/AdminPasswordResetRequest.java, mashup-domain/src/main/java/kr/mashup/branding/repository/adminmember/AdminMemberRepository.java, mashup-domain/src/main/java/kr/mashup/branding/service/adminmember/AdminMemberService.java
=> feature: fix admin api

.gitignore, mashup-admin/src/main/java/kr/mashup/branding/facade/member/MemberFacadeService.java, mashup-admin/src/main/java/kr/mashup/branding/ui/adminmember/AdminMemberController.java, mashup-admin/src/main/java/kr/mashup/branding/ui/member/MemberController.java, mashup-admin/src/main/java/kr/mashup/branding/ui/member/request/MemberDropOutRequest.java, mashup-admin/src/main/java/kr/mashup/branding/ui/member/request/MemberTransferRequest.java, mashup-admin/src/main/java/kr/mashup/branding/ui/member/response/MemberResponse.java, mashup-domain/src/main/java/kr/mashup/branding/domain/adminmember/entity/AdminMember.java, mashup-domain/src/main/java/kr/mashup/branding/domain/generation/Generation.java, mashup-domain/src/main/java/kr/mashup/branding/domain/member/CurrentMemberStatus.java, mashup-domain/src/main/java/kr/mashup/branding/domain/member/MemberGeneration.java, mashup-domain/src/main/java/kr/mashup/branding/domain/member/MemberGenerationStatus.java, mashup-domain/src/main/java/kr/mashup/branding/repository/member/MemberGenerationRepositoryCustom.java, mashup-domain/src/main/java/kr/mashup/branding/repository/member/MemberGenerationRepositoryCustomImpl.java, mashup-domain/src/main/java/kr/mashup/branding/repository/member/MemberRepository.java, mashup-domain/src/main/java/kr/mashup/branding/repository/member/MemberRepositoryCustom.java, mashup-domain/src/main/java/kr/mashup/branding/repository/member/MemberRepositoryCustomImpl.java, mashup-domain/src/main/java/kr/mashup/branding/service/member/CurrentMemberStatusCalculationService.java, mashup-domain/src/main/java/kr/mashup/branding/service/member/MemberCreateDto.java, mashup-domain/src/main/java/kr/mashup/branding/service/member/MemberService.java, mashup-member/src/main/java/kr/mashup/branding/facade/member/MemberFacadeService.java
=> add transfer api

mashup-recruit/src/main/java/kr/mashup/branding/config/security/SecurityConfig.java, mashup-recruit/src/main/java/kr/mashup/branding/ui/team/TeamResponse.java
=> feat: fix response and api

mashup-recruit/src/main/java/kr/mashup/branding/ui/scheduler/ConfirmationScheduler.java
=> feat: fix scheduler

mashup-recruit/src/main/java/kr/mashup/branding/config/security/SecurityConfig.java
=> feat: fix auth

mashup-recruit/src/main/java/kr/mashup/branding/ui/team/TeamResponse.java
=> feat: remove lower case

mashup-admin/src/main/java/kr/mashup/branding/facade/schedule/ScheduleFacadeService.java, mashup-admin/src/main/java/kr/mashup/branding/ui/schedule/request/ScheduleCreateRequest.java, mashup-admin/src/main/java/kr/mashup/branding/ui/schedule/request/ScheduleUpdateRequest.java, mashup-admin/src/main/java/kr/mashup/branding/ui/schedule/response/ScheduleResponse.java, mashup-domain/src/main/java/kr/mashup/branding/domain/schedule/Location.java, mashup-domain/src/main/java/kr/mashup/branding/domain/schedule/Schedule.java, mashup-domain/src/main/java/kr/mashup/branding/domain/schedule/ScheduleCreateDto.java, mashup-domain/src/main/java/kr/mashup/branding/service/schedule/ScheduleService.java, mashup-member/src/main/java/kr/mashup/branding/ui/schedule/response/ScheduleResponse.java
- 스케줄 장소 주소/장소명 추가
- Location에 address/placeName추가
=> 스케줄 장소 주소/장소명 추가

mashup-admin/src/main/java/kr/mashup/branding/ui/schedule/request/ScheduleCreateRequest.java, mashup-admin/src/main/java/kr/mashup/branding/ui/schedule/request/ScheduleUpdateRequest.java, mashup-domain/src/main/java/kr/mashup/branding/service/schedule/ScheduleService.java
- 스케줄 location 온라인 대응 가능하게 추가
- location 관련값 중 하나라도 null이 들어오면 zoom으로 저장하게 변경
=> 스케줄 location 온라인 대응 가능하게 추가

mashup-domain/src/main/java/kr/mashup/branding/domain/schedule/Schedule.java
- 스케줄 온라인 판단 메서드를 수정합니다.
- 온라인인 경우에도 placeName 이 존재할 수 있어, 해당 메서드를 수정합니다.
=> feat: 스케줄 온라인 판단 메서드 수정

mashup-member/src/main/java/kr/mashup/branding/ui/member/response/MemberProfileResponse.java
=> feat: 멤버 기수 정보 조회 시에 기수 역순 정렬 수정

mashup-domain/src/main/java/kr/mashup/branding/service/schedule/ScheduleService.java
=> 스케줄 업데이트 시 온라인 대응 가능하게 수정

mashup-member/src/main/java/kr/mashup/branding/facade/member/MemberFacadeService.java
=> fix: 토큰 생성 시 가장 최근의 기수로 생성되도록 수정

mashup-domain/src/main/java/kr/mashup/branding/repository/attendance/AttendanceRepository.java, mashup-domain/src/main/java/kr/mashup/branding/service/member/MemberService.java
=> fix: 회원 탈퇴 시, Attendance 데이터 삭제처리

mashup-domain/src/main/java/kr/mashup/branding/repository/member/MemberRepositoryCustomImpl.java, mashup-member/src/main/java/kr/mashup/branding/facade/attendance/AttendanceFacadeService.java, mashup-member/src/main/java/kr/mashup/branding/ui/attendance/response/AttendanceInfo.java
- 스케줄 시작전인 경우, 빈 배열이 아닌 NOT_YET 이 응답되도록 수정
- 현재 활동하고 있는 기수 조회 쿼리 수정(같은 경우도 추가)
=> fix: OT 에서 발생했던 이슈 수정

mashup-admin/src/main/java/kr/mashup/branding/ui/schedule/ScheduleController.java, mashup-domain/src/main/java/kr/mashup/branding/service/schedule/ScheduleService.java
=> 주소/장소명 40자 초과 시 예외 처리 추가

mashup-admin/src/main/java/kr/mashup/branding/facade/schedule/ScheduleFacadeService.java, mashup-admin/src/main/java/kr/mashup/branding/ui/schedule/request/ScheduleCreateRequest.java, mashup-admin/src/main/java/kr/mashup/branding/ui/schedule/request/ScheduleUpdateRequest.java, mashup-domain/src/main/java/kr/mashup/branding/domain/schedule/Location.java, mashup-domain/src/main/java/kr/mashup/branding/domain/schedule/ScheduleCreateDto.java, mashup-domain/src/main/java/kr/mashup/branding/service/schedule/ScheduleService.java
- Schedule Location 필드 이름 detailAddress, roadAddress 로 변경
=> Schedule Location 필드 이름 detailAddress, roadAddress 로 변경

mashup-admin/src/main/java/kr/mashup/branding/ui/schedule/ScheduleController.java, mashup-domain/src/main/java/kr/mashup/branding/repository/schedule/ScheduleRepositoryCustomImpl.java
=> fix: change schedule order

mashup-admin/src/main/java/kr/mashup/branding/ui/schedule/request/ScheduleCreateRequest.java, mashup-admin/src/main/java/kr/mashup/branding/ui/schedule/request/ScheduleUpdateRequest.java
=> fix : fix git error

mashup-domain/src/main/resources/application-develop.yml
=> feat: 개발 DB URL 변경

mashup-admin/src/main/java/kr/mashup/branding/facade/schedule/ScheduleFacadeService.java, mashup-domain/src/main/java/kr/mashup/branding/domain/ResultCode.java, mashup-domain/src/main/java/kr/mashup/branding/domain/schedule/exception/ScheduleNotUpdatableException.java, mashup-domain/src/main/java/kr/mashup/branding/repository/attendance/AttendanceRepository.java, mashup-domain/src/main/java/kr/mashup/branding/service/schedule/ScheduleService.java
=> fix: 출석이 존재하면 스케줄 변경 못하게 변경

mashup-admin/src/main/java/kr/mashup/branding/facade/schedule/ScheduleFacadeService.java, mashup-domain/src/main/java/kr/mashup/branding/domain/ResultCode.java, mashup-domain/src/main/java/kr/mashup/branding/domain/schedule/exception/ScheduleNotUpdatableException.java, mashup-domain/src/main/java/kr/mashup/branding/repository/attendance/AttendanceRepository.java, mashup-domain/src/main/java/kr/mashup/branding/service/schedule/ScheduleService.java, mashup-member/src/main/java/kr/mashup/branding/ui/schedule/response/LocationResponse.java, mashup-member/src/main/java/kr/mashup/branding/ui/schedule/response/ScheduleResponse.java
=> 멤버 스케줄 조회 API 응답 임시 수정

mashup-domain/src/main/java/kr/mashup/branding/domain/schedule/Schedule.java
=> feat: ANDROID 타입 추가

mashup-domain/src/main/java/kr/mashup/branding/domain/rnb/RnbMeta.java, mashup-domain/src/main/java/kr/mashup/branding/domain/rnb/RnbPolicy.java, mashup-domain/src/main/java/kr/mashup/branding/repository/rnb/RnbMetaRepository.java, mashup-domain/src/main/java/kr/mashup/branding/service/generation/GenerationService.java, mashup-domain/src/main/java/kr/mashup/branding/service/member/MemberService.java, mashup-domain/src/main/java/kr/mashup/branding/service/rnb/RnbMetaService.java, mashup-domain/src/test/java/kr/mashup/branding/service/rnb/RnbMetaServiceTest.java, mashup-member/src/main/java/kr/mashup/branding/facade/member/MemberFacadeService.java, mashup-member/src/main/java/kr/mashup/branding/facade/member/MemberProfileFacadeService.java, mashup-member/src/main/java/kr/mashup/branding/facade/rnb/RnbMetaFacadeService.java, mashup-member/src/main/java/kr/mashup/branding/ui/rnb/MetaController.java, mashup-member/src/main/java/kr/mashup/branding/ui/rnb/response/RnbMetaResponse.java, mashup-member/src/test/java/kr/mashup/branding/facade/rnb/RnbMetaFacadeServiceTest.java
=> feat: add rnb meta api

mashup-domain/src/main/java/kr/mashup/branding/domain/ResultCode.java, mashup-domain/src/main/java/kr/mashup/branding/domain/mashong/MashongPopcorn.java, mashup-domain/src/main/java/kr/mashup/branding/domain/mashong/PlatformMashong.java, mashup-domain/src/main/java/kr/mashup/branding/domain/mashong/PlatformMashongLevel.java, mashup-domain/src/main/java/kr/mashup/branding/repository/mashong/PlatformMashongLevelRepository.java, mashup-domain/src/main/java/kr/mashup/branding/repository/mashong/PlatformMashongRepository.java, mashup-domain/src/main/java/kr/mashup/branding/service/mashong/MashongPopcornService.java, mashup-domain/src/main/java/kr/mashup/branding/service/mashong/PlatformMashongService.java, mashup-member/src/main/java/kr/mashup/branding/facade/mashong/MashongFacadeService.java, mashup-member/src/main/java/kr/mashup/branding/ui/mashong/MashongController.java, mashup-member/src/main/java/kr/mashup/branding/ui/mashong/MashongMissionController.java, mashup-member/src/main/java/kr/mashup/branding/ui/mashong/request/MashongFeedRequest.java, mashup-member/src/main/java/kr/mashup/branding/ui/mashong/response/MashongFeedResponse.java
=> 매숑이 팝콘 주기 기능 구현

mashup-admin/src/main/java/kr/mashup/branding/ui/pushnoti/PushNotiEventListener.java, mashup-batch/src/main/java/kr/mashup/branding/ui/pushnoti/PushNotiEventListener.java, mashup-domain/src/main/java/kr/mashup/branding/domain/member/Member.java, mashup-domain/src/main/java/kr/mashup/branding/domain/pushhistory/PushHistory.java, mashup-domain/src/main/java/kr/mashup/branding/repository/pushhistory/PushHistoryRepository.java, mashup-domain/src/main/java/kr/mashup/branding/service/member/MemberService.java, mashup-domain/src/main/java/kr/mashup/branding/service/pushhistory/PushHistoryService.java, mashup-member/src/main/java/kr/mashup/branding/facade/pushhistory/PushHistoryFacadeService.java, mashup-member/src/main/java/kr/mashup/branding/ui/pushhistory/PushHistoryController.java, mashup-member/src/main/java/kr/mashup/branding/ui/pushhistory/response/PushHistoriesResponse.java, mashup-member/src/main/java/kr/mashup/branding/ui/pushnoti/PushNotiEventListener.java
=> feat: add push history

mashup-member/src/main/java/kr/mashup/branding/facade/pushhistory/PushHistoryFacadeService.java, mashup-member/src/main/java/kr/mashup/branding/facade/rnb/RnbMetaFacadeService.java, mashup-member/src/main/java/kr/mashup/branding/ui/pushhistory/PushHistoryController.java
=> fix bug and add push not check api

mashup-domain/src/main/java/kr/mashup/branding/domain/mashong/MashongMission.java, mashup-member/src/main/java/kr/mashup/branding/facade/mashong/MashongFacadeService.java, mashup-member/src/main/java/kr/mashup/branding/facade/mashong/MashongMissionFacadeService.java
=> 매숑이 팝콘 줄 때 mission log 쌓기 구현

mashup-admin/src/main/resources/logback/logback-spring.xml, mashup-batch/src/main/resources/logback/logback-spring.xml, mashup-member/src/main/resources/logback/logback-spring.xml, mashup-recruit/src/main/resources/logback/logback-spring.xml
- createLogGroup 을 추가
- 이미 존재하는 로그 그룹에 새로 생성하려고 하면서, 에러가 발생하고 있음
=> feat: createLogGroup 을 추가

mashup-admin/src/main/java/kr/mashup/branding/facade/schedule/ScheduleFacadeService.java, mashup-admin/src/main/java/kr/mashup/branding/ui/schedule/request/ScheduleCreateRequest.java, mashup-admin/src/main/java/kr/mashup/branding/ui/schedule/request/ScheduleUpdateRequest.java, mashup-domain/src/main/java/kr/mashup/branding/domain/schedule/Schedule.java, mashup-domain/src/main/java/kr/mashup/branding/domain/schedule/ScheduleCreateDto.java, mashup-domain/src/main/java/kr/mashup/branding/service/schedule/ScheduleService.java, mashup-member/src/main/java/kr/mashup/branding/ui/schedule/response/ScheduleResponse.java
=> feat: 공지 추가

mashup-domain/src/main/java/kr/mashup/branding/domain/ResultCode.java, mashup-domain/src/main/java/kr/mashup/branding/domain/mashong/PlatformMashong.java, mashup-domain/src/main/java/kr/mashup/branding/repository/mashong/PlatformMashongLevelRepository.java, mashup-domain/src/main/java/kr/mashup/branding/service/mashong/PlatformMashongLevelService.java, mashup-domain/src/main/java/kr/mashup/branding/service/mashong/PlatformMashongService.java, mashup-member/src/main/java/kr/mashup/branding/facade/mashong/MashongFacadeService.java, mashup-member/src/main/java/kr/mashup/branding/ui/mashong/MashongController.java, mashup-member/src/main/java/kr/mashup/branding/ui/mashong/request/MashongLevelUpRequest.java, mashup-member/src/main/java/kr/mashup/branding/ui/mashong/response/MashongLevelUpResponse.java
=> 매숑이 레벨업 분리

mashup-domain/src/main/java/kr/mashup/branding/domain/mashong/PlatformMashong.java, mashup-domain/src/main/java/kr/mashup/branding/service/mashong/PlatformMashongService.java, mashup-domain/src/main/java/kr/mashup/branding/service/mashong/dto/LevelUpResult.java, mashup-member/src/main/java/kr/mashup/branding/facade/mashong/MashongFacadeService.java, mashup-member/src/main/java/kr/mashup/branding/ui/mashong/response/MashongLevelUpResponse.java
=> 매숑이 레벨업 미션 로그 구현

mashup-domain/src/main/java/kr/mashup/branding/domain/mashong/PlatformMashong.java, mashup-member/src/main/java/kr/mashup/branding/facade/mashong/MashongFacadeService.java, mashup-member/src/main/java/kr/mashup/branding/ui/mashong/MashongController.java, mashup-member/src/main/java/kr/mashup/branding/ui/mashong/response/MashongFeedResponse.java, mashup-member/src/main/java/kr/mashup/branding/ui/mashong/response/PlatformMashongStatusResponse.java
=> 플랫폼 매숑이 상태 조회 구현

mashup-domain/src/main/java/kr/mashup/branding/domain/mashong/PlatformMashong.java, mashup-member/src/main/java/kr/mashup/branding/facade/mashong/MashongFacadeService.java
=> fix: 매숑이 레벨업 기준 현재 레벨의 goalValue로 수정

mashup-domain/src/main/java/kr/mashup/branding/domain/mashong/PlatformMashong.java
=> fix: 팝콘 먼저 뺀 후 레벨업하게 수정

mashup-member/src/main/java/kr/mashup/branding/facade/mashong/MashongMissionFacadeService.java, mashup-member/src/main/java/kr/mashup/branding/ui/mashong/MashongMissionController.java, mashup-member/src/main/java/kr/mashup/branding/ui/mashong/response/MashongAttendanceResponse.java
=> 매숑이 출석 현황 확인 API 구현

mashup-domain/src/main/java/kr/mashup/branding/domain/popup/PopupType.java, mashup-domain/src/main/java/kr/mashup/branding/service/member/MemberProfileService.java, mashup-member/src/main/java/kr/mashup/branding/facade/birthday/BirthdayFacadeService.java, mashup-member/src/main/java/kr/mashup/branding/facade/popup/MemberPopupFacadeService.java, mashup-member/src/main/java/kr/mashup/branding/ui/member/response/MemberBirthdaysResponse.java, mashup-member/src/main/java/kr/mashup/branding/ui/popup/MemberPopupController.java
- 생일 당사자인 경우, 생일 축하 팝업을 보여주기 위해 타입 추가
=> feat: 생일자 팝업 추가

mashup-member/src/main/java/kr/mashup/branding/ui/member/response/MemberBirthdaysResponse.java
=> feat: 내림차순으로 변경

mashup-domain/src/main/java/kr/mashup/branding/repository/member/MemberProfileRepositoryCustom.java, mashup-domain/src/main/java/kr/mashup/branding/repository/member/MemberProfileRepositoryCustomImpl.java, mashup-domain/src/main/java/kr/mashup/branding/service/member/MemberBirthdayDto.java, mashup-domain/src/main/java/kr/mashup/branding/service/member/MemberProfileService.java, mashup-member/src/main/java/kr/mashup/branding/facade/birthday/BirthdayFacadeService.java, mashup-member/src/main/java/kr/mashup/branding/ui/member/response/MemberBirthdayResponse.java, mashup-member/src/main/java/kr/mashup/branding/ui/member/response/MemberBirthdaysResponse.java
- 생일자 조회 시에 월 / 일만 비교하도록 변경합니다.
=> fix: 월 일만 비교하도록 변경

mashup-member/src/main/java/kr/mashup/branding/facade/mashong/MashongMissionFacadeService.java
=> synchronize

mashup-domain/src/main/java/kr/mashup/branding/domain/scorehistory/ScoreType.java
=> dev to master

mashup-domain/build.gradle, mashup-domain/src/main/java/kr/mashup/branding/config/S3Config.java, mashup-domain/src/main/java/kr/mashup/branding/service/birthday/FileService.java, mashup-domain/src/main/resources/application-develop.yml, mashup-domain/src/main/resources/application-local.yml, mashup-domain/src/main/resources/application-production.yml, mashup-member/src/main/java/kr/mashup/branding/facade/birthday/BirthdayCardFacadeService.java, mashup-member/src/main/java/kr/mashup/branding/ui/birthday/BirthdayCardController.java, mashup-member/src/main/java/kr/mashup/branding/ui/birthday/response/BirthdayCardDefaultImagesResponse.java, mashup-member/src/main/java/kr/mashup/branding/ui/birthday/response/BirthdayCardImageResponse.java, mashup-member/src/main/resources/member-develop.yml, mashup-member/src/main/resources/member-local.yml, mashup-member/src/main/resources/member-production.yml
=> feat: 나만의 생일 축하 카드 생성을 위한 presigned url 발급 API

mashup-domain/src/main/java/kr/mashup/branding/domain/ResultCode.java, mashup-domain/src/main/java/kr/mashup/branding/service/birthday/BirthdayCardService.java, mashup-member/src/main/java/kr/mashup/branding/ui/birthday/request/BirthdayCardRequest.java
=> feat: 생일 카드 생성 시에 removeQueryParameters 추가

mashup-recruit/src/main/java/kr/mashup/branding/ui/scheduler/ConfirmationScheduler.java
=> feat: Recruitment Schedule 대응

mashup-admin/build.gradle, mashup-admin/src/main/java/kr/mashup/branding/facade/application/AdminApplicationExcelFacadeService.java, mashup-admin/src/main/java/kr/mashup/branding/ui/application/AdminApplicationExcelController.java, mashup-admin/src/main/java/kr/mashup/branding/util/ExcelGenerator.java, mashup-domain/src/main/java/kr/mashup/branding/service/application/ApplicationService.java
=> feat: 지원서 엑셀 다운로드 기능 추가

mashup-admin/Dockerfile
=> feat: 이미지에 폰트를 설치하도록 Dockerfile을 수정

mashup-admin/Dockerfile
=> feat: 도커 이미지 변경

mashup-member/src/main/java/kr/mashup/branding/facade/attendance/AttendanceFacadeService.java
=> feat: fix push target bug

.github/workflows/ci-dev-admin.yml, .github/workflows/ci-dev-member.yml, .github/workflows/ci-dev-recruit.yml, .github/workflows/ci-prod-admin.yml, .github/workflows/ci-prod-member.yml, .github/workflows/ci-prod-recruit.yml
=> fix: setup-java version upgrade
